name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 5
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies using Yarn
      run: yarn
    
    - name: Get .env file from within the system
      run: |
        cd /home/fonature/cancanfoodapp-api/foodapp-backend/fyp21S313-CanIsCan-backend/fyp21S313-CanIsCan-backend
        cp /home/fonature/cancanfoodapp-api/foodapp-backend/.env /home/fonature/cancanfoodapp-api/foodapp-backend/fyp21S313-CanIsCan-backend/fyp21S313-CanIsCan-backend

    - name: Stop and start pm2 service
      run: |
        pm2 stop 4
        pm2 start 4
        pm2 save